/** The Types describe what is happening in the application and are used by the dispatch to communicate with the Reducer */
export const SUCCESSFUL_REGISTRATION = 'SUCCESSFUL_REGISTRATION';
export const ERRONEOUS_REGISTRATION = 'ERRONEOUS_REGISTRATION';

export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN';
export const ERRONEOUS_LOGIN = 'ERRONEOUS_LOGIN';

export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';

export const SIGN_OFF = 'SIGN_OFF';

export const SHOW_ALERT_COMPONENT = 'SHOW_ALERT_COMPONENT';
export const HIDE_ALERT_COMPONENT = 'HIDE_ALERT_COMPONENT';

export const UPLOADING_FILE = 'UPLOADING_FILE';
export const SUCESSFUL_FILE_UPLOAD = 'SUCESSFUL_FILE_UPLOAD';
export const ERRONEOUS_FILE_UPLOAD = 'ERRONEOUS_FILE_UPLOAD';

export const LINK_SUCCESSFULLY_CREATED = 'LINK_SUCCESSFULLY_CREATED';
export const ERROR_CREATING_LINK = 'ERROR_CREATING_LINK';